### ISSUE TITLE
Dependency is not satisfiable: libhiredis0.10 (>= 0.10.1)

### ISSUE THREAD

**Issue by yizhiheying** [Wabel/zoho-crm-orm#11]
eason@eason-virtual-machine:~/webrtc/turnserver$ sudo gdebi coturn*.deb
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: libhiredis0.10 (>= 0.10.1)

This issue said libhiredis not satisfiable.
but redis is setup ok in ubuntu 15.10.

eason@eason-virtual-machine:~/webrtc/turnserver$ redis-cli --version
redis-cli 2.8.20
eason@eason-virtual-machine:~/webrtc/turnserver$ redis-server --version
Redis server v=2.8.20 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=e6e1ebeb848dc6c4

Anyone can help?

**Comment by moufmouf** [comment]
Hey @yizhiheying,

I really don't see how this relates (at all) to zoho-crm-orm, which is a PHP library that has nothing to do with Redis.

Closing this now.

**Comment by LeonanCarvalho** [comment]
apt-get install libhiredis-dev
