### ISSUE TITLE
Make Zoho Url configurable

### ISSUE THREAD

**Issue by loertel** [Wabel/zoho-crm-orm#28]
Zoho offers eu servers with separated auth tokens:
zoho.**eu** != zoho.**com**

if this call works:  https://crm.zoho.eu/crm/private/xml/Leads/getRecords?authtoken=XXXXX&scope=crmapi 

this call throws invalid id: https://crm.zoho.com/crm/private/xml/Leads/getRecords?authtoken=XXXXX&scope=crmapi

**Comment by moufmouf** [comment]
Fixed in #32
